In [1]:
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # 텐서플로가 첫 번째 GPU에 1GB 메모리만 할당하도록 제한
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=2500)])
  except RuntimeError as e:
    # 프로그램 시작시에 가상 장치가 설정되어야만 합니다
    print(e)

In [2]:
seq_len = 512

In [3]:
perm_size = 128

In [5]:
index = tf.range(seq_len, dtype=tf.int64)

In [6]:
index

<tf.Tensor: shape=(512,), dtype=int64, numpy=
array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 1

In [12]:
index = tf.transpose(tf.reshape(index, [-1, perm_size]))

In [13]:
index

<tf.Tensor: shape=(128, 4), dtype=int64, numpy=
array([[  0, 128, 256, 384],
       [  1, 129, 257, 385],
       [  2, 130, 258, 386],
       [  3, 131, 259, 387],
       [  4, 132, 260, 388],
       [  5, 133, 261, 389],
       [  6, 134, 262, 390],
       [  7, 135, 263, 391],
       [  8, 136, 264, 392],
       [  9, 137, 265, 393],
       [ 10, 138, 266, 394],
       [ 11, 139, 267, 395],
       [ 12, 140, 268, 396],
       [ 13, 141, 269, 397],
       [ 14, 142, 270, 398],
       [ 15, 143, 271, 399],
       [ 16, 144, 272, 400],
       [ 17, 145, 273, 401],
       [ 18, 146, 274, 402],
       [ 19, 147, 275, 403],
       [ 20, 148, 276, 404],
       [ 21, 149, 277, 405],
       [ 22, 150, 278, 406],
       [ 23, 151, 279, 407],
       [ 24, 152, 280, 408],
       [ 25, 153, 281, 409],
       [ 26, 154, 282, 410],
       [ 27, 155, 283, 411],
       [ 28, 156, 284, 412],
       [ 29, 157, 285, 413],
       [ 30, 158, 286, 414],
       [ 31, 159, 287, 415],
       [ 32, 160, 288, 4

In [14]:
index2 = tf.reshape(index, [perm_size, -1])

In [15]:
index2

<tf.Tensor: shape=(128, 4), dtype=int64, numpy=
array([[  0, 128, 256, 384],
       [  1, 129, 257, 385],
       [  2, 130, 258, 386],
       [  3, 131, 259, 387],
       [  4, 132, 260, 388],
       [  5, 133, 261, 389],
       [  6, 134, 262, 390],
       [  7, 135, 263, 391],
       [  8, 136, 264, 392],
       [  9, 137, 265, 393],
       [ 10, 138, 266, 394],
       [ 11, 139, 267, 395],
       [ 12, 140, 268, 396],
       [ 13, 141, 269, 397],
       [ 14, 142, 270, 398],
       [ 15, 143, 271, 399],
       [ 16, 144, 272, 400],
       [ 17, 145, 273, 401],
       [ 18, 146, 274, 402],
       [ 19, 147, 275, 403],
       [ 20, 148, 276, 404],
       [ 21, 149, 277, 405],
       [ 22, 150, 278, 406],
       [ 23, 151, 279, 407],
       [ 24, 152, 280, 408],
       [ 25, 153, 281, 409],
       [ 26, 154, 282, 410],
       [ 27, 155, 283, 411],
       [ 28, 156, 284, 412],
       [ 29, 157, 285, 413],
       [ 30, 158, 286, 414],
       [ 31, 159, 287, 415],
       [ 32, 160, 288, 4

In [17]:
index = tf.random.shuffle(index)

In [18]:
index

<tf.Tensor: shape=(128, 4), dtype=int64, numpy=
array([[ 27, 155, 283, 411],
       [ 71, 199, 327, 455],
       [113, 241, 369, 497],
       [  3, 131, 259, 387],
       [112, 240, 368, 496],
       [ 50, 178, 306, 434],
       [ 90, 218, 346, 474],
       [ 70, 198, 326, 454],
       [ 86, 214, 342, 470],
       [ 84, 212, 340, 468],
       [ 93, 221, 349, 477],
       [ 23, 151, 279, 407],
       [ 83, 211, 339, 467],
       [ 35, 163, 291, 419],
       [ 80, 208, 336, 464],
       [116, 244, 372, 500],
       [ 74, 202, 330, 458],
       [ 77, 205, 333, 461],
       [105, 233, 361, 489],
       [ 41, 169, 297, 425],
       [ 61, 189, 317, 445],
       [114, 242, 370, 498],
       [  8, 136, 264, 392],
       [ 60, 188, 316, 444],
       [ 13, 141, 269, 397],
       [108, 236, 364, 492],
       [ 51, 179, 307, 435],
       [ 58, 186, 314, 442],
       [ 68, 196, 324, 452],
       [ 87, 215, 343, 471],
       [115, 243, 371, 499],
       [ 12, 140, 268, 396],
       [  9, 137, 265, 3

In [19]:
index = tf.reshape(tf.transpose(index), [-1])

In [20]:
index

<tf.Tensor: shape=(512,), dtype=int64, numpy=
array([ 27,  71, 113,   3, 112,  50,  90,  70,  86,  84,  93,  23,  83,
        35,  80, 116,  74,  77, 105,  41,  61, 114,   8,  60,  13, 108,
        51,  58,  68,  87, 115,  12,   9,  59,  65,  98,  21,  72,  81,
        46,  82,  42, 111, 117, 109,  64,  16,   4, 107, 124,  49,  94,
       100,  53,  73,  62,  76,  75, 110,  79,  66, 118,  10,  47, 106,
         6, 121,  56,  18,  95,  25,  69,  33, 104,   5,  54, 122, 103,
        92,  15, 123,  91,   0,  28,  89,  20, 119,  37, 125, 127,  67,
        57,  97,  34,  45,  30,  14,  31,  55,  63,  48,  40,  78,  52,
        17,  36,  43,   2,  24,  88,  32,  22, 102, 101,  85,  44,  29,
        99,  96,  38, 120,  39,   1,  19,  26, 126,  11,   7, 155, 199,
       241, 131, 240, 178, 218, 198, 214, 212, 221, 151, 211, 163, 208,
       244, 202, 205, 233, 169, 189, 242, 136, 188, 141, 236, 179, 186,
       196, 215, 243, 140, 137, 187, 193, 226, 149, 200, 209, 174, 210,
       170, 239, 2